//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordStore.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlbumRecording
    {
        public int AlbumRecordingID { get; set; }
        public int AlbumID { get; set; }
        public int RecordingID { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Recording Recording { get; set; }
    }
}
