//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordStore.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Album()
        {
            this.AlbumArtist = new HashSet<AlbumArtist>();
            this.AlbumGenre = new HashSet<AlbumGenre>();
            this.AlbumRecording = new HashSet<AlbumRecording>();
        }
    
        public int AlbumID { get; set; }
        public string AlbumName { get; set; }
        public string Description { get; set; }
        public int LabelID { get; set; }
        public bool CompilationAlbum { get; set; }
        public string CatalogNum { get; set; }
        public Nullable<decimal> Price { get; set; }
        public bool IsInPrint { get; set; }
        public int FormatID { get; set; }
        public Nullable<int> UnitsInStock { get; set; }
        public int AlbumStatusID { get; set; }
        public string AlbumImage { get; set; }
        public Nullable<int> Num { get; set; }
        public Nullable<int> Tracks { get; set; }
        public Nullable<bool> IsFeatured { get; set; }
        public Nullable<int> Year { get; set; }
        public string AlbumNameSort { get; set; }
        public string RearImage { get; set; }
        public Nullable<int> ChannelID { get; set; }
    
        public virtual AlbumStatus AlbumStatus { get; set; }
        public virtual Format Format { get; set; }
        public virtual Label Label { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlbumArtist> AlbumArtist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlbumGenre> AlbumGenre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlbumRecording> AlbumRecording { get; set; }
        public virtual Channel Channel { get; set; }
    }
}
